# Generated by Django 3.2 on 2022-02-05 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0004_alter_producto_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('solicitado', 'SOLICITADO'), ('pagado', 'PAGADO')], default='solicitado', max_length=20),
        ),
        migrations.AddField(
            model_name='pedido',
            name='nro_recibo',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='pedido',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
