# Generated by Django 4.0.2 on 2022-02-05 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Favorito',
            fields=[
                ('favorito_id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(default='', max_length=200, verbose_name='TITULO')),
                ('url', models.CharField(default='', max_length=200, verbose_name='URL')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='FECHA')),
            ],
        ),
    ]
