CREATE DATABASE IF NOT EXISTS company;

USE company;

CREATE Table employee(  
    id INT(11) NOT NULL AUTO_INCREMENT,
    name VARCHAR(255) DEFAULT NULL,
    salary INT(11) DEFAULT NULL,
    PRIMARY KEY(id)
);

INSERT INTO employee(name,salary) VALUES
('CESAR RUSSO',7000),
('PEDRO PACAS',7000),
('LUIS PEROL',7000);
